#!/usr/bin/env python3
"""
Generate a network map from contacts across all applications.

Parses contacts.md files in applications/*/
Outputs a Mermaid diagram + text summary to network-map.md in repo root.

Usage:
    scripts/network-map.py [--name NAME] [--json]

Options:
    --name NAME   Filter to a single application directory
    --json        Output raw data as JSON instead of Markdown
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    print("❌ PyYAML required: pip install pyyaml")
    sys.exit(1)

from lib.common import REPO_ROOT


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _load_meta(app_dir: Path) -> dict:
    meta_path = app_dir / "meta.yml"
    if not meta_path.exists():
        return {}
    with open(meta_path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _parse_contacts(contacts_path: Path) -> list[dict]:
    """Parse contacts.md, returning list of {name, email, title, source}."""
    if not contacts_path.exists():
        return []

    text    = contacts_path.read_text(encoding="utf-8")
    contacts = []
    seen    = set()

    # Pattern: name — title — email  (from Website section)
    for m in re.finditer(
        r"[-•]\s+(.+?)\s+[—–]\s+(.+?)\s+[—–]\s+([\w.+-]+@[\w.-]+)", text
    ):
        name, title, email = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
        if email not in seen:
            contacts.append({"name": name, "title": title, "email": email, "source": "website"})
            seen.add(email)

    # Pattern: table row: | Name | Email | Position | Confidence |
    for m in re.finditer(
        r"\|\s*([^|]+?)\s*\|\s*([\w.+-]+@[\w.-]+)\s*\|\s*([^|]+?)\s*\|", text
    ):
        name, email, title = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
        if email not in seen and name.lower() not in ("name", "---"):
            contacts.append({"name": name, "title": title, "email": email, "source": "hunter"})
            seen.add(email)

    # Pattern: @handle — email (GitHub)
    for m in re.finditer(r"[-•]\s+(@\S+)\s+[—–]\s+([\w.+-]+@[\w.-]+)", text):
        handle, email = m.group(1).strip(), m.group(2).strip()
        if email not in seen:
            contacts.append({"name": handle, "title": "GitHub", "email": email, "source": "github"})
            seen.add(email)

    # Primary contact line
    m = re.search(r"Primary\s+contact[:\s]+(.+?)\s+<([\w.+-]+@[\w.-]+)>", text, re.I)
    if m:
        name, email = m.group(1).strip(), m.group(2).strip()
        for c in contacts:
            if c["email"] == email:
                c["primary"] = True
                break
        else:
            if email not in seen:
                contacts.append({"name": name, "title": "", "email": email,
                                 "source": "manual", "primary": True})
                seen.add(email)

    return contacts


def collect_network(apps_dir: Path, name_filter: str = "") -> list[dict]:
    """Collect network data from all applications."""
    nodes = []
    for d in sorted(apps_dir.iterdir()):
        if not d.is_dir():
            continue
        if name_filter and name_filter.lower() not in d.name.lower():
            continue

        meta     = _load_meta(d)
        company  = meta.get("company", d.name)
        outcome  = meta.get("outcome", "")
        position = meta.get("position", "")
        contacts = _parse_contacts(d / "contacts.md")

        if contacts:
            nodes.append({
                "app":      d.name,
                "company":  company,
                "position": position,
                "outcome":  outcome,
                "contacts": contacts,
            })

    return nodes


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

_SOURCE_ICON = {
    "hunter":  "🔍",
    "website": "🌐",
    "github":  "🐙",
    "manual":  "✍️",
}

_OUTCOME_COLOR = {
    "offer":    "#2ecc71",
    "rejected": "#e74c3c",
    "ghosted":  "#95a5a6",
    "interview":"#3498db",
    "":         "#f39c12",
}


def build_mermaid(nodes: list[dict]) -> str:
    """Generate Mermaid graph."""
    lines = ["graph LR"]
    lines.append("    %% Network Map — generated by network-map.py")

    company_ids: dict[str, str] = {}
    contact_ids: dict[str, str] = {}
    ctr = [0]

    def _id(prefix: str) -> str:
        ctr[0] += 1
        return f"{prefix}{ctr[0]}"

    for node in nodes:
        company = node["company"]
        if company not in company_ids:
            cid = _id("C")
            company_ids[company] = cid
            lines.append(f"    {cid}[🏢 {company}]")

        cid = company_ids[company]
        for contact in node["contacts"]:
            email = contact.get("email", "")
            name  = contact.get("name", "?")
            title = contact.get("title", "")
            icon  = _SOURCE_ICON.get(contact.get("source", ""), "")
            key   = email or name

            if key not in contact_ids:
                pid = _id("P")
                contact_ids[key] = pid
                label = f"{icon} {name}"
                if title and title.lower() not in ("github",):
                    label += f"\\n{title[:30]}"
                lines.append(f"    {pid}([\"{label}\"])")
                lines.append(f"    {cid} --> {pid}")

    return "\n".join(lines)


def build_markdown(nodes: list[dict]) -> str:
    today = date.today().isoformat()
    total_contacts = sum(len(n["contacts"]) for n in nodes)

    lines = [
        "# Network Map",
        f"*{len(nodes)} companies · {total_contacts} contacts · Updated: {today}*",
        "",
        "---",
        "",
    ]

    # Mermaid diagram
    if nodes:
        lines += [
            "## Diagram",
            "",
            "```mermaid",
            build_mermaid(nodes),
            "```",
            "",
        ]

    # Text summary per company
    lines += ["## Contacts by Company", ""]

    for node in nodes:
        company  = node["company"]
        position = node["position"]
        outcome  = node["outcome"]
        contacts = node["contacts"]

        outcome_badge = f" · {outcome}" if outcome else ""
        lines += [
            f"### {company}",
            f"*{position}{outcome_badge}*",
            "",
        ]
        if not contacts:
            lines.append("*No contacts found.*\n")
            continue

        lines.append("| Name | Title | Email | Source |")
        lines.append("|------|-------|-------|--------|")
        for c in contacts:
            icon  = _SOURCE_ICON.get(c.get("source", ""), "")
            name  = c.get("name", "")
            if c.get("primary"):
                name = f"**{name}** ⭐"
            lines.append(
                f"| {name} | {c.get('title', '')} | "
                f"{c.get('email', '')} | {icon} {c.get('source', '')} |"
            )
        lines.append("")

    # All emails flat list
    all_contacts: list[dict] = []
    seen_emails: set[str] = set()
    for node in nodes:
        for c in node["contacts"]:
            e = c.get("email", "")
            if e and e not in seen_emails:
                all_contacts.append({**c, "company": node["company"]})
                seen_emails.add(e)

    if all_contacts:
        lines += [
            "---",
            "## All Contacts (flat list)",
            "",
        ]
        for c in all_contacts:
            star = " ⭐" if c.get("primary") else ""
            lines.append(
                f"- **{c.get('name','')}**{star} — {c.get('title','')} "
                f"@ {c.get('company','')}  "
                f"`{c.get('email','')}`"
            )
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate network map from contacts")
    parser.add_argument("--name", default="", help="Filter to one application")
    parser.add_argument("--json", action="store_true", help="Output JSON data")
    args = parser.parse_args()

    apps_dir = REPO_ROOT / "applications"
    if not apps_dir.exists():
        print("❌ applications/ directory not found")
        return 1

    nodes = collect_network(apps_dir, name_filter=args.name)

    if args.json:
        print(json.dumps(nodes, indent=2, ensure_ascii=False))
        return 0

    total = sum(len(n["contacts"]) for n in nodes)
    print(f"🌐 Network Map — {len(nodes)} companies, {total} contacts")

    if not nodes:
        print("   No contacts.md files found. Run: make contacts NAME=...")
        return 0

    md = build_markdown(nodes)

    out_path = REPO_ROOT / "network-map.md"
    out_path.write_text(md, encoding="utf-8")
    print(f"✅ Saved to {out_path}")

    # Print summary to terminal
    for node in nodes:
        print(f"\n   🏢 {node['company']} ({len(node['contacts'])} contacts)")
        for c in node["contacts"]:
            star = " ⭐" if c.get("primary") else ""
            print(f"      • {c.get('name','')}{star} — {c.get('email','')}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
