#!/usr/bin/env python3
"""
Smart follow-up scheduler — automatically create GitHub Issues for stale applications.

Reads all applications, computes days since application date, and creates
GitHub Issues with follow-up templates at D+7, D+14, and D+30 thresholds.

Thresholds:
  D+7  : gentle follow-up reminder
  D+14 : stale application warning
  D+30 : archive candidate

Usage:
    scripts/smart-followup.py [--dry-run] [--threshold DAYS] [--create-issues]
    make smart-followup
    make smart-followup DRY=1
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("❌ PyYAML required: pip install pyyaml")
    sys.exit(1)

from lib.common import REPO_ROOT

# Applications with these outcomes are considered closed — skip follow-up
CLOSED_OUTCOMES = {"rejected", "ghosted", "withdrawn", "accepted", "declined", "archived"}

# Thresholds for follow-up tiers
THRESHOLDS = {
    7: ("D+7", "gentle", "🟡"),
    14: ("D+14", "stale", "🟠"),
    30: ("D+30", "archive candidate", "🔴"),
}


def _parse_date(val: str | None) -> date | None:
    """Parse YYYY-MM or YYYY-MM-DD into a date object."""
    if not val:
        return None
    val = str(val).strip()
    for fmt in ("%Y-%m-%d", "%Y-%m"):
        try:
            return datetime.strptime(val, fmt).date()
        except ValueError:
            continue
    return None


def _days_since(d: date) -> int:
    return (date.today() - d).days


def load_applications(apps_dir: Path) -> list[dict]:
    records = []
    for app_dir in sorted(apps_dir.iterdir()):
        if not app_dir.is_dir():
            continue
        meta_path = app_dir / "meta.yml"
        if not meta_path.exists():
            continue
        try:
            meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
        except Exception:
            continue

        outcome = str(meta.get("outcome", "applied")).lower()
        if outcome in CLOSED_OUTCOMES:
            continue

        # Determine application date: prefer 'applied' field, fall back to 'created'
        applied_raw = meta.get("applied") or meta.get("created")
        app_date = _parse_date(str(applied_raw) if applied_raw else None)
        if not app_date:
            # Try to infer from directory name (YYYY-MM-company)
            parts = app_dir.name.split("-")
            if len(parts) >= 2:
                app_date = _parse_date(f"{parts[0]}-{parts[1]}")

        if not app_date:
            continue

        days = _days_since(app_date)
        company = meta.get("company", app_dir.name)
        position = meta.get("position", "")
        provider = meta.get("tailor_provider", "")

        # Determine highest triggered threshold
        tier = None
        for threshold in sorted(THRESHOLDS):
            if days >= threshold:
                tier = threshold

        if tier is None:
            continue  # Not yet past first threshold

        records.append(
            {
                "name": app_dir.name,
                "company": company,
                "position": position,
                "outcome": outcome,
                "provider": provider,
                "app_date": str(app_date),
                "days": days,
                "tier": tier,
                "tier_label": THRESHOLDS[tier][0],
                "tier_desc": THRESHOLDS[tier][1],
                "tier_emoji": THRESHOLDS[tier][2],
                "has_issue": (meta.get("followup_issue") is not None),
                "followup_issue": meta.get("followup_issue"),
            }
        )

    return records


def _issue_title(rec: dict) -> str:
    return f"[Follow-up {rec['tier_label']}] {rec['company']} — {rec['position']}"


def _issue_body(rec: dict) -> str:
    return f"""## Follow-up: {rec["company"]}

**Position**: {rec["position"]}
**Applied**: {rec["app_date"]} ({rec["days"]} days ago)
**Status**: {rec["outcome"]} — {rec["tier_desc"]}
**AI Provider**: {rec["provider"] or "n/a"}
**Branch**: `apply/{rec["name"]}`

### Action items

- [ ] Check for any reply (email, LinkedIn, ATS portal)
- [ ] Send follow-up email if no response received
- [ ] Update `meta.yml` outcome when resolved
- [ ] Run `make notify NAME={rec["name"]} STATUS=rejected` if no longer active

### Follow-up email template

> Subject: Re: {rec["position"]} Application — {rec["company"]}
>
> Hi [Recruiter],
>
> I wanted to follow up on my application for the {rec["position"]} role submitted on {rec["app_date"]}.
> I'm still very interested in the opportunity and would welcome the chance to connect.
>
> Best regards,
> [Your name]

---
_Auto-generated by `make smart-followup` on {date.today()}_
"""


def _save_issue_number(app_dir: Path, issue_number: int) -> None:
    """Record the GitHub issue number in meta.yml."""
    meta_path = app_dir / "meta.yml"
    try:
        meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
        meta["followup_issue"] = issue_number
        with open(meta_path, "w", encoding="utf-8") as f:
            yaml.dump(meta, f, allow_unicode=True, sort_keys=False)
    except Exception:
        pass


def create_github_issue(rec: dict, apps_dir: Path, dry_run: bool) -> int | None:
    """Create a GitHub Issue and return the issue number."""
    title = _issue_title(rec)
    body = _issue_body(rec)
    label = f"follow-up:{rec['tier_label'].lower()}"

    if dry_run:
        print(f'      [DRY] gh issue create --title "{title[:60]}..."')
        return None

    try:
        result = subprocess.run(
            ["gh", "issue", "create", "--title", title, "--body", body, "--label", "follow-up"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            # Extract issue number from URL (https://github.com/owner/repo/issues/42)
            url = result.stdout.strip()
            issue_num = int(url.rstrip("/").split("/")[-1]) if url else None
            if issue_num:
                _save_issue_number(apps_dir / rec["name"], issue_num)
                return issue_num
            return None
        else:
            err = result.stderr.strip()[:120]
            print(f"      ⚠️  gh issue create failed: {err}")
            return None
    except FileNotFoundError:
        print("      ⚠️  gh CLI not found — install: https://cli.github.com/")
        return None
    except Exception as e:
        print(f"      ⚠️  Error: {e}")
        return None


def print_report(records: list[dict]) -> None:
    print(f"\n{'SMART FOLLOW-UP REPORT':=^72}")
    print(f"  {len(records)} applications need follow-up\n")

    for tier in sorted(THRESHOLDS):
        tier_recs = [r for r in records if r["tier"] == tier]
        if not tier_recs:
            continue
        label, desc, emoji = THRESHOLDS[tier]
        print(f"  {emoji} {label} — {desc} ({len(tier_recs)} apps)")
        for r in tier_recs:
            issue_str = f" [GH#{r['followup_issue']}]" if r.get("followup_issue") else ""
            print(f"     {r['name']:<38} {r['days']:>3}d{issue_str}")
            print(f"     {r['company']} — {r['position'][:45]}")
        print()


def main() -> int:
    parser = argparse.ArgumentParser(description="Smart follow-up scheduler for stale applications")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done without writing")
    parser.add_argument("--create-issues", action="store_true", help="Create GitHub Issues for new stale applications")
    parser.add_argument("--threshold", type=int, default=7, help="Minimum days before flagging (default: 7)")
    parser.add_argument("--json", action="store_true", dest="json_mode", help="Output JSON")
    args = parser.parse_args()

    apps_dir = REPO_ROOT / "applications"
    if not apps_dir.is_dir():
        print("❌ applications/ directory not found")
        return 1

    records = load_applications(apps_dir)

    # Filter by threshold
    records = [r for r in records if r["days"] >= args.threshold]

    if args.json_mode:
        print(json.dumps(records, indent=2))
        return 0

    if not records:
        print(f"✅ No applications past {args.threshold} days without response.")
        return 0

    print_report(records)

    if args.create_issues or args.dry_run:
        new_records = [r for r in records if not r["has_issue"]]
        if not new_records:
            print("  ℹ️  All stale applications already have GitHub Issues.")
            return 0

        print(f"  Creating {len(new_records)} GitHub Issue(s){'  [DRY RUN]' if args.dry_run else ''}...\n")
        for rec in new_records:
            print(f"  {rec['tier_emoji']} {rec['name']}")
            issue_num = create_github_issue(rec, apps_dir, args.dry_run)
            if issue_num:
                print(f"      ✅ Created GH#{issue_num}")
    else:
        print(f"  💡 Run `make smart-followup CREATE=1` to create GitHub Issues\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
