// Package storage handles filesystem reads and writes for the CV project.
//
// Security:
//   - All paths are resolved relative to CV_PATH and validated
//   - Application names are checked against a strict regex
//   - No symlink following (filepath.EvalSymlinks prevents escaping)
//   - File reads are bounded by size limits
package storage

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/jsoyer/cv-api/internal/cvutil"
	"github.com/jsoyer/cv-api/internal/models"
	"github.com/jsoyer/cv-api/internal/search"
	"gopkg.in/yaml.v3"
)

const (
	applicationsDir = "applications"
	metaFile        = "meta.yml"
	notesFile       = "notes.md"
	settingsFile    = "settings.json"
	maxFileSize     = 10 * 1024 * 1024 // 10 MB max per file read
)

// allowedUploadExts lists extensions accepted by UploadFile and ReadFileRaw.
var allowedUploadExts = map[string]bool{
	".txt":  true,
	".pdf":  true,
	".md":   true,
	".yml":  true,
	".yaml": true,
	".docx": true,
}

// extContentTypes maps allowed extensions to their MIME type.
var extContentTypes = map[string]string{
	".txt":  "text/plain; charset=utf-8",
	".pdf":  "application/pdf",
	".md":   "text/markdown; charset=utf-8",
	".yml":  "text/yaml; charset=utf-8",
	".yaml": "text/yaml; charset=utf-8",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}

// skillsStopwords are common words excluded from keyword analysis.
var skillsStopwords = map[string]bool{
	"with": true, "that": true, "this": true, "will": true, "have": true,
	"from": true, "they": true, "been": true, "your": true, "more": true,
	"work": true, "team": true, "able": true, "also": true, "such": true,
	"good": true, "well": true, "high": true, "into": true, "time": true,
	"some": true, "must": true, "role": true, "what": true, "both": true,
	"when": true, "their": true, "other": true, "using": true, "about": true,
}

// nonAlphaNum matches any character that is not a letter or digit.
var nonAlphaNum = regexp.MustCompile(`[^a-z0-9]+`)

// applicationMeta mirrors the real meta.yml structure generated by the CV Makefile.
// Fields match the actual YAML keys used in applications/*/meta.yml.
type applicationMeta struct {
	Company      string   `yaml:"company"`
	Position     string   `yaml:"position"`
	Created      string   `yaml:"created"`
	Applied      string   `yaml:"applied,omitempty"`
	Outcome      string   `yaml:"outcome,omitempty"`
	Deadline     *string  `yaml:"deadline,omitempty"`
	ResponseDays *int     `yaml:"response_days,omitempty"`
	FollowupDate *string  `yaml:"followup_date,omitempty"`
	TechStack    []string `yaml:"tech_stack,omitempty"`
}

// knownFiles are the files we expose from each application directory.
var knownFiles = []string{
	"meta.yml",
	"job.txt",
	"job.url",
	"cv-tailored.yml",
	"coverletter.yml",
	"prep.md",
	"company-research.md",
	"contacts.md",
	"star-stories.md",
	"salary-bench.md",
	"interview-brief.md",
	"milestones.yml",
}

// Storage handles filesystem reads for the CV project.
type Storage struct {
	cvPath   string
	appLocks sync.Map // map[string]*sync.Mutex, keyed by application name
	idx      *search.Index
}

// New creates a Storage rooted at the CV project path.
func New(cvPath string) *Storage {
	s := &Storage{
		cvPath: cvPath,
		idx:    search.New(),
	}
	_ = s.RebuildIndex() // best-effort; errors are non-fatal at startup
	return s
}

// RebuildIndex rebuilds the in-memory full-text search index from all applications.
func (s *Storage) RebuildIndex() error {
	apps, err := s.ListApplications()
	if err != nil {
		return fmt.Errorf("rebuild index: list applications: %w", err)
	}
	for _, app := range apps {
		notes, _ := s.ReadNotes(app.Name)
		text := strings.Join([]string{app.Name, app.Company, app.Position, notes}, " ")
		s.idx.Add(app.Name, text)
	}
	return nil
}

// lockApp returns the mutex for the named application and an unlock function.
// Concurrent calls for the same name serialize on the same mutex.
func (s *Storage) lockApp(name string) (*sync.Mutex, func()) {
	v, _ := s.appLocks.LoadOrStore(name, &sync.Mutex{})
	mu := v.(*sync.Mutex)
	mu.Lock()
	return mu, mu.Unlock
}

// ListApplications reads all application directories and returns their metadata.
func (s *Storage) ListApplications() ([]models.Application, error) {
	appsDir := filepath.Join(s.cvPath, applicationsDir)
	entries, err := os.ReadDir(appsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []models.Application{}, nil
		}
		return nil, fmt.Errorf("read applications dir: %w", err)
	}

	var apps []models.Application
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if err := cvutil.ValidateAppName(name); err != nil {
			continue // skip invalid directory names
		}
		app, err := s.readAppMeta(name)
		if err != nil {
			continue // skip apps with broken metadata
		}
		apps = append(apps, *app)
	}

	sort.Slice(apps, func(i, j int) bool {
		return apps[i].CreatedAt.After(apps[j].CreatedAt)
	})

	return apps, nil
}

// ListApplicationsPage loads all applications, applies the filter and sort from f,
// then returns a page starting after the cursor. It returns the page slice, the
// total count of matching applications (pre-slice), and the next-page cursor
// (empty string when the returned page is the last one).
func (s *Storage) ListApplicationsPage(cursor string, limit int, f models.ApplicationFilter) ([]models.Application, int, string, error) {
	if limit <= 0 {
		limit = 20
	}
	if limit > 100 {
		limit = 100
	}

	apps, err := s.ListApplications()
	if err != nil {
		return nil, 0, "", err
	}

	// Apply filters.
	filtered := apps[:0:0] // reuse backing array
	lowerCompany := strings.ToLower(f.Company)
	for _, app := range apps {
		if f.Status != "" && app.Status != f.Status {
			continue
		}
		if f.Company != "" && !strings.Contains(strings.ToLower(app.Company), lowerCompany) {
			continue
		}
		if f.DateFrom != "" {
			t, err := time.Parse("2006-01", f.DateFrom)
			if err == nil && app.CreatedAt.Before(t) {
				continue
			}
		}
		if f.DateTo != "" {
			t, err := time.Parse("2006-01", f.DateTo)
			if err == nil {
				// Include the whole target month by comparing against the first of the next month.
				endOfMonth := t.AddDate(0, 1, 0)
				if !app.CreatedAt.Before(endOfMonth) {
					continue
				}
			}
		}
		filtered = append(filtered, app)
	}

	// Sort.
	sortField := f.Sort
	if sortField == "" {
		sortField = "created_at"
	}
	desc := f.Order != "asc"

	sort.SliceStable(filtered, func(i, j int) bool {
		var less bool
		switch sortField {
		case "deadline":
			di := filtered[i].Deadline
			dj := filtered[j].Deadline
			switch {
			case di == nil && dj == nil:
				less = false
			case di == nil:
				less = false
			case dj == nil:
				less = true
			default:
				less = di.Before(*dj)
			}
		case "company":
			less = strings.ToLower(filtered[i].Company) < strings.ToLower(filtered[j].Company)
		case "status":
			less = filtered[i].Status < filtered[j].Status
		default: // created_at
			less = filtered[i].CreatedAt.Before(filtered[j].CreatedAt)
		}
		if desc {
			return !less
		}
		return less
	})

	total := len(filtered)

	// Find cursor position and slice.
	start := 0
	if cursor != "" {
		for idx, app := range filtered {
			if app.Name == cursor {
				start = idx + 1
				break
			}
		}
	}

	var page []models.Application
	if start >= len(filtered) {
		page = []models.Application{}
	} else {
		page = filtered[start:]
	}

	nextCursor := ""
	if len(page) > limit {
		nextCursor = page[limit-1].Name
		page = page[:limit]
	}

	return page, total, nextCursor, nil
}

// GetApplication reads a single application with all associated files.
func (s *Storage) GetApplication(name string) (*models.Application, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	app, err := s.readAppMeta(name)
	if err != nil {
		return nil, err
	}

	app.Files = make(map[string]string)
	for _, fname := range knownFiles {
		fpath := filepath.Join(appDir, fname)
		content, err := s.safeReadFile(fpath)
		if err != nil {
			continue // file may not exist
		}
		app.Files[fname] = content
	}

	return app, nil
}

// CreateApplication creates a new application directory with meta.yml.
func (s *Storage) CreateApplication(company, position, url string) (*models.Application, error) {
	now := time.Now()
	dirName := fmt.Sprintf("%s-%s", now.Format("2006-01"), sanitizeDirName(company))

	if err := cvutil.ValidateAppName(dirName); err != nil {
		return nil, fmt.Errorf("generated name is invalid: %w", err)
	}

	appDir := filepath.Join(s.cvPath, applicationsDir, dirName)
	if err := os.MkdirAll(appDir, 0750); err != nil {
		return nil, fmt.Errorf("create directory: %w", err)
	}

	meta := applicationMeta{
		Company: company,
		Position: position,
		Created: now.Format("2006-01"),
	}

	data, err := yaml.Marshal(&meta)
	if err != nil {
		return nil, fmt.Errorf("marshal meta: %w", err)
	}

	metaPath := filepath.Join(appDir, metaFile)
	if err := os.WriteFile(metaPath, data, 0640); err != nil {
		return nil, fmt.Errorf("write meta.yml: %w", err)
	}

	if url != "" {
		urlPath := filepath.Join(appDir, "job.url")
		if err := os.WriteFile(urlPath, []byte(url), 0640); err != nil {
			return nil, fmt.Errorf("write job.url: %w", err)
		}
	}

	app := &models.Application{
		Name:      dirName,
		Company:   company,
		Position:  position,
		Status:    "applied",
		CreatedAt: now,
	}
	s.idx.Add(dirName, strings.Join([]string{dirName, company, position}, " "))
	return app, nil
}

// ReadSettings reads settings.json from the CV project root.
func (s *Storage) ReadSettings() (*models.Settings, error) {
	path := filepath.Join(s.cvPath, settingsFile)
	content, err := s.safeReadFile(path)
	if err != nil {
		// Return defaults if file doesn't exist
		return &models.Settings{
			Theme:       "dark",
			DefaultView: "dashboard",
		}, nil
	}

	var settings models.Settings
	if err := json.Unmarshal([]byte(content), &settings); err != nil {
		return nil, fmt.Errorf("parse settings: %w", err)
	}
	return &settings, nil
}

// WriteSettings saves settings.json to the CV project root.
func (s *Storage) WriteSettings(settings models.Settings) error {
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal settings: %w", err)
	}
	path := filepath.Join(s.cvPath, settingsFile)
	return os.WriteFile(path, data, 0640)
}

// GetDashboard returns aggregated dashboard data.
func (s *Storage) GetDashboard() (*models.DashboardData, error) {
	apps, err := s.ListApplications()
	if err != nil {
		return nil, err
	}

	byStatus := make(map[string]int)
	for _, app := range apps {
		byStatus[app.Status]++
	}

	recent := apps
	if len(recent) > 10 {
		recent = recent[:10]
	}

	return &models.DashboardData{
		TotalApplications:  len(apps),
		ByStatus:           byStatus,
		RecentApplications: recent,
	}, nil
}

// GetStats returns pipeline statistics.
func (s *Storage) GetStats() (*models.StatsData, error) {
	apps, err := s.ListApplications()
	if err != nil {
		return nil, err
	}

	funnel := make(map[string]int)
	timeline := make(map[string]int)

	for _, app := range apps {
		funnel[app.Status]++
		month := app.CreatedAt.Format("2006-01")
		timeline[month]++
	}

	var entries []models.TimelineEntry
	for date, count := range timeline {
		entries = append(entries, models.TimelineEntry{Date: date, Count: count})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Date < entries[j].Date
	})

	return &models.StatsData{
		Funnel:   funnel,
		Timeline: entries,
	}, nil
}

// UpdateApplication patches writable fields in meta.yml and returns the updated Application.
// Uses map[string]any for read-modify-write to preserve unknown fields (tech_stack, etc.).
func (s *Storage) UpdateApplication(name string, req models.UpdateApplicationRequest) (*models.Application, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	_, unlock := s.lockApp(name)
	defer unlock()

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	metaPath := filepath.Join(appDir, metaFile)
	content, err := s.safeReadFile(metaPath)
	if err != nil {
		return nil, fmt.Errorf("read meta.yml for %s: %w", name, err)
	}

	// Use map to preserve all existing fields (tech_stack, applied, etc.)
	var raw map[string]any
	if err := yaml.Unmarshal([]byte(content), &raw); err != nil {
		return nil, fmt.Errorf("parse meta.yml for %s: %w", name, err)
	}
	if raw == nil {
		raw = make(map[string]any)
	}

	if req.Status != nil {
		raw["outcome"] = *req.Status
	}
	if req.Company != nil {
		raw["company"] = *req.Company
	}
	if req.Position != nil {
		raw["position"] = *req.Position
	}
	if req.FollowupDate != nil {
		raw["followup_date"] = *req.FollowupDate
	}
	if req.Deadline != nil {
		raw["deadline"] = *req.Deadline
	}

	data, err := yaml.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal meta.yml for %s: %w", name, err)
	}

	if err := os.WriteFile(metaPath, data, 0640); err != nil {
		return nil, fmt.Errorf("write meta.yml for %s: %w", name, err)
	}

	updated, err := s.readAppMeta(name)
	if err != nil {
		return nil, err
	}
	notes, _ := s.ReadNotes(name)
	s.idx.Add(name, strings.Join([]string{name, updated.Company, updated.Position, notes}, " "))
	return updated, nil
}

// ReadNotes returns the content of notes.md for the given application.
func (s *Storage) ReadNotes(name string) (string, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return "", err
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return "", err
	}

	path := filepath.Join(appDir, notesFile)
	content, err := s.safeReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read notes for %s: %w", name, err)
	}
	return content, nil
}

// WriteNotes writes content to notes.md for the given application.
func (s *Storage) WriteNotes(name string, content string) error {
	if err := cvutil.ValidateAppName(name); err != nil {
		return err
	}

	_, unlock := s.lockApp(name)
	defer unlock()

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return err
	}

	path := filepath.Join(appDir, notesFile)
	if err := os.WriteFile(path, []byte(content), 0640); err != nil {
		return fmt.Errorf("write notes for %s: %w", name, err)
	}
	return nil
}

const (
	versionsDir     = ".versions"
	maxNoteVersions = 10
)

// NoteVersion holds metadata about a historical version of notes.md.
type NoteVersion struct {
	Filename  string    `json:"filename"`
	SavedAt   time.Time `json:"saved_at"`
	SizeBytes int64     `json:"size_bytes"`
}

// WriteNotesVersioned writes notes and saves the previous version in a
// .versions/ subdirectory before overwriting. At most 10 versions are kept;
// the oldest are pruned when the limit is exceeded.
func (s *Storage) WriteNotesVersioned(name, content string) error {
	if err := cvutil.ValidateAppName(name); err != nil {
		return err
	}

	_, unlock := s.lockApp(name)
	defer unlock()

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return err
	}

	notesPath := filepath.Join(appDir, notesFile)
	existing, readErr := os.ReadFile(notesPath)

	if readErr == nil && len(existing) > 0 {
		vDir := filepath.Join(appDir, versionsDir)
		if mkErr := os.MkdirAll(vDir, 0750); mkErr != nil {
			return fmt.Errorf("create versions dir for %s: %w", name, mkErr)
		}

		ts := time.Now().UTC().Format("20060102T150405Z")
		vFilename := "notes-" + ts + ".md"
		vPath := filepath.Join(vDir, vFilename)
		if wErr := os.WriteFile(vPath, existing, 0640); wErr != nil {
			return fmt.Errorf("write version snapshot for %s: %w", name, wErr)
		}

		if pErr := s.pruneNoteVersions(vDir); pErr != nil {
			return fmt.Errorf("prune versions for %s: %w", name, pErr)
		}
	}

	if err := os.WriteFile(notesPath, []byte(content), 0640); err != nil {
		return fmt.Errorf("write notes for %s: %w", name, err)
	}
	app, _ := s.readAppMeta(name)
	if app != nil {
		s.idx.Add(name, strings.Join([]string{name, app.Company, app.Position, content}, " "))
	}
	return nil
}

// pruneNoteVersions removes the oldest version files if there are more than
// maxNoteVersions entries in the given directory.
func (s *Storage) pruneNoteVersions(vDir string) error {
	entries, err := os.ReadDir(vDir)
	if err != nil {
		return err
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	for len(names) > maxNoteVersions {
		oldest := names[0]
		names = names[1:]
		if rmErr := os.Remove(filepath.Join(vDir, oldest)); rmErr != nil {
			return rmErr
		}
	}
	return nil
}

// ListNoteVersions returns version metadata for an application's notes,
// sorted oldest first.
func (s *Storage) ListNoteVersions(name string) ([]NoteVersion, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	vDir := filepath.Join(appDir, versionsDir)
	entries, err := os.ReadDir(vDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []NoteVersion{}, nil
		}
		return nil, fmt.Errorf("read versions dir for %s: %w", name, err)
	}

	var versions []NoteVersion
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		info, infoErr := e.Info()
		if infoErr != nil {
			continue
		}
		nv := NoteVersion{
			Filename:  e.Name(),
			SavedAt:   info.ModTime().UTC(),
			SizeBytes: info.Size(),
		}
		versions = append(versions, nv)
	}

	sort.Slice(versions, func(i, j int) bool {
		return versions[i].Filename < versions[j].Filename
	})

	if versions == nil {
		return []NoteVersion{}, nil
	}
	return versions, nil
}

// ReadNoteVersion reads a specific historical version of notes by filename.
func (s *Storage) ReadNoteVersion(name, filename string) ([]byte, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	filename = filepath.Base(filename)

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	vDir := filepath.Join(appDir, versionsDir)
	vPath := filepath.Join(vDir, filename)

	info, err := os.Stat(vPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("version %q not found", filename)
		}
		return nil, fmt.Errorf("stat version file: %w", err)
	}
	if info.Size() > maxFileSize {
		return nil, fmt.Errorf("version file exceeds max size")
	}

	data, err := os.ReadFile(vPath)
	if err != nil {
		return nil, fmt.Errorf("read version %s for %s: %w", filename, name, err)
	}
	return data, nil
}

// UploadFile validates the extension and writes data to the application directory.
func (s *Storage) UploadFile(name, filename string, data []byte) error {
	if err := cvutil.ValidateAppName(name); err != nil {
		return err
	}

	_, unlock := s.lockApp(name)
	defer unlock()

	filename = filepath.Base(filename)
	ext := strings.ToLower(filepath.Ext(filename))
	if !allowedUploadExts[ext] {
		return fmt.Errorf("invalid extension %q: only .txt, .pdf, .md, .yml, .yaml, .docx are allowed", ext)
	}
	if int64(len(data)) > maxFileSize {
		return fmt.Errorf("file exceeds maximum allowed size of %d bytes", maxFileSize)
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return err
	}

	path := filepath.Join(appDir, filename)
	if err := os.WriteFile(path, data, 0640); err != nil {
		return fmt.Errorf("write file %s for %s: %w", filename, name, err)
	}
	return nil
}

// ReadFileRaw returns the raw bytes and content-type of a file in the application directory.
func (s *Storage) ReadFileRaw(name, filename string) ([]byte, string, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, "", err
	}

	filename = filepath.Base(filename)
	ext := strings.ToLower(filepath.Ext(filename))
	if !allowedUploadExts[ext] {
		return nil, "", fmt.Errorf("invalid extension %q: file not allowed", ext)
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, "", err
	}

	path := filepath.Join(appDir, filename)
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, "", fmt.Errorf("file %q not found", filename)
		}
		return nil, "", fmt.Errorf("stat file %s: %w", filename, err)
	}
	if info.Size() > maxFileSize {
		return nil, "", fmt.Errorf("file %s exceeds max size (%d bytes)", filename, maxFileSize)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", fmt.Errorf("read file %s for %s: %w", filename, name, err)
	}

	ct := extContentTypes[ext]
	if ct == "" {
		ct = "application/octet-stream"
	}
	return data, ct, nil
}

// SkillsGap tokenizes job.txt and data/cv.yml, then returns missing and present keywords.
func (s *Storage) SkillsGap(name string) (*models.SkillsGapResponse, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	jobPath := filepath.Join(appDir, "job.txt")
	jobContent, err := s.safeReadFile(jobPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("job.txt not found for application %q", name)
		}
		return nil, fmt.Errorf("read job.txt for %s: %w", name, err)
	}

	cvPath := filepath.Join(s.cvPath, "data", "cv.yml")
	cvContent, err := s.safeReadFile(cvPath)
	if err != nil {
		return nil, fmt.Errorf("read cv.yml: %w", err)
	}

	jobTokens := tokenize(jobContent)
	cvTokens := tokenize(cvContent)

	var missing, present []string
	for token := range jobTokens {
		if cvTokens[token] {
			present = append(present, token)
		} else {
			missing = append(missing, token)
		}
	}

	sort.Strings(missing)
	sort.Strings(present)

	return &models.SkillsGapResponse{
		Missing: missing,
		Present: present,
	}, nil
}

// tokenize lowercases text, strips non-alphanumeric characters, and returns
// a set of words with a minimum length of 4 that are not stopwords.
func tokenize(text string) map[string]bool {
	lower := strings.ToLower(text)
	words := strings.Fields(nonAlphaNum.ReplaceAllString(lower, " "))

	set := make(map[string]bool, len(words))
	for _, w := range words {
		if len(w) < 4 {
			continue
		}
		if skillsStopwords[w] {
			continue
		}
		set[w] = true
	}
	return set
}

// searchFiles are the files searched by the Search method.
var searchFiles = []string{"job.txt", "prep.md", "company-research.md", "notes.md"}

// Search performs case-insensitive full-text search across application files.
// Returns up to maxResults matching applications with snippets.
// It uses the in-memory index for candidate selection when the index is non-empty,
// falling back to a linear scan otherwise.
func (s *Storage) Search(query string, maxResults int) (*models.SearchResponse, error) {
	if maxResults <= 0 {
		maxResults = 20
	}

	lowerQuery := strings.ToLower(query)

	// Try the index first to narrow candidates.
	candidates := s.idx.Search(query, maxResults)

	var apps []models.Application
	if len(candidates) > 0 {
		for _, name := range candidates {
			app, err := s.readAppMeta(name)
			if err != nil {
				continue
			}
			apps = append(apps, *app)
		}
	} else {
		// Fall back to linear scan (index empty or no hits).
		all, err := s.ListApplications()
		if err != nil {
			return nil, err
		}
		apps = all
	}

	var results []models.SearchResult

	for _, app := range apps {
		if len(results) >= maxResults {
			break
		}

		appDir, err := s.resolveAppDir(app.Name)
		if err != nil {
			continue
		}

		var matches []models.SearchMatch
		for _, fname := range searchFiles {
			fpath := filepath.Join(appDir, fname)
			content, err := s.safeReadFile(fpath)
			if err != nil {
				continue
			}
			if i := strings.Index(strings.ToLower(content), lowerQuery); i >= 0 {
				snippet := getSnippet(content, i, len(query), 120)
				matches = append(matches, models.SearchMatch{File: fname, Snippet: snippet})
			}
		}

		if len(matches) > 0 {
			results = append(results, models.SearchResult{
				Name:     app.Name,
				Company:  app.Company,
				Position: app.Position,
				Stage:    app.Status,
				Matches:  matches,
			})
		}
	}

	return &models.SearchResponse{Results: results}, nil
}

// getSnippet extracts a context window around a match position.
func getSnippet(text string, matchIdx, matchLen, radius int) string {
	start := matchIdx - radius
	if start < 0 {
		start = 0
	}
	end := matchIdx + matchLen + radius
	if end > len(text) {
		end = len(text)
	}
	snippet := text[start:end]
	if start > 0 {
		snippet = "…" + snippet
	}
	if end < len(text) {
		snippet = snippet + "…"
	}
	return snippet
}

const (
	healthScoresFile    = ".health-scores.yml"
	maxHealthScores     = 30
)

// ScoreEntry records an audit score at a point in time.
type ScoreEntry struct {
	CheckedAt           time.Time `json:"checked_at" yaml:"checked_at"`
	QuantificationScore float64   `json:"quantification_score" yaml:"quantification_score"`
	ActionVerbScore     float64   `json:"action_verb_score" yaml:"action_verb_score"`
	CompletenessScore   float64   `json:"completeness_score" yaml:"completeness_score"`
	OverallScore        float64   `json:"overall_score" yaml:"overall_score"`
}

// AppendHealthScore stores a score entry for the named application.
// At most maxHealthScores entries are kept; oldest entries are dropped when
// the limit is exceeded.
func (s *Storage) AppendHealthScore(name string, entry ScoreEntry) error {
	if err := cvutil.ValidateAppName(name); err != nil {
		return err
	}

	_, unlock := s.lockApp(name)
	defer unlock()

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return err
	}

	scores, _ := s.readHealthScores(appDir)
	scores = append(scores, entry)
	if len(scores) > maxHealthScores {
		scores = scores[len(scores)-maxHealthScores:]
	}

	data, err := yaml.Marshal(scores)
	if err != nil {
		return fmt.Errorf("marshal health scores for %s: %w", name, err)
	}

	path := filepath.Join(appDir, healthScoresFile)
	if err := os.WriteFile(path, data, 0640); err != nil {
		return fmt.Errorf("write health scores for %s: %w", name, err)
	}
	return nil
}

// ListHealthScores returns all stored score entries for the named application.
func (s *Storage) ListHealthScores(name string) ([]ScoreEntry, error) {
	if err := cvutil.ValidateAppName(name); err != nil {
		return nil, err
	}

	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	scores, err := s.readHealthScores(appDir)
	if err != nil {
		return nil, err
	}
	if scores == nil {
		return []ScoreEntry{}, nil
	}
	return scores, nil
}

// readHealthScores reads the .health-scores.yml file for an application directory.
// It silently returns an empty slice when the file does not yet exist.
func (s *Storage) readHealthScores(appDir string) ([]ScoreEntry, error) {
	path := filepath.Join(appDir, healthScoresFile)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return []ScoreEntry{}, nil
		}
		return nil, fmt.Errorf("read health scores: %w", err)
	}
	var scores []ScoreEntry
	if err := yaml.Unmarshal(data, &scores); err != nil {
		return nil, fmt.Errorf("parse health scores: %w", err)
	}
	if scores == nil {
		return []ScoreEntry{}, nil
	}
	return scores, nil
}

func (s *Storage) readAppMeta(name string) (*models.Application, error) {
	appDir, err := s.resolveAppDir(name)
	if err != nil {
		return nil, err
	}

	metaPath := filepath.Join(appDir, metaFile)
	content, err := s.safeReadFile(metaPath)
	if err != nil {
		return nil, fmt.Errorf("read meta.yml for %s: %w", name, err)
	}

	var meta applicationMeta
	if err := yaml.Unmarshal([]byte(content), &meta); err != nil {
		return nil, fmt.Errorf("parse meta.yml for %s: %w", name, err)
	}

	// Parse created date: try YYYY-MM-DD first, then YYYY-MM (Makefile format)
	createdAt, _ := time.Parse("2006-01-02", meta.Created)
	if createdAt.IsZero() {
		createdAt, _ = time.Parse("2006-01", meta.Created)
	}

	// Status is derived from outcome; default to "applied" if empty
	status := meta.Outcome
	if status == "" {
		status = "applied"
	}

	app := &models.Application{
		Name:      name,
		Company:   meta.Company,
		Position:  meta.Position,
		Status:    status,
		CreatedAt: createdAt,
		Outcome:   meta.Outcome,
	}

	if meta.Deadline != nil {
		if t, err := time.Parse("2006-01-02", *meta.Deadline); err == nil {
			app.Deadline = &t
		}
	}

	return app, nil
}

// resolveAppDir returns the absolute path to an application directory,
// validating it stays within the applications directory (no symlink escape).
func (s *Storage) resolveAppDir(name string) (string, error) {
	appsDir := filepath.Join(s.cvPath, applicationsDir)
	appDir := filepath.Join(appsDir, name)

	resolved, err := filepath.EvalSymlinks(appDir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("application %q not found", name)
		}
		return "", fmt.Errorf("resolve path for %s: %w", name, err)
	}

	resolvedApps, err := filepath.EvalSymlinks(appsDir)
	if err != nil {
		return "", fmt.Errorf("resolve applications dir: %w", err)
	}

	if !strings.HasPrefix(resolved, resolvedApps+string(os.PathSeparator)) {
		return "", fmt.Errorf("path traversal detected for %q", name)
	}

	return resolved, nil
}

// safeReadFile reads a file with size limits.
func (s *Storage) safeReadFile(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if info.Size() > maxFileSize {
		return "", fmt.Errorf("file %s exceeds max size (%d bytes)", path, maxFileSize)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// sanitizeDirName creates a filesystem-safe directory name from a company name.
func sanitizeDirName(name string) string {
	name = strings.ToLower(name)
	name = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r == ' ' || r == '_' {
			return '-'
		}
		return -1
	}, name)
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}
	name = strings.Trim(name, "-")
	if len(name) > 50 {
		name = name[:50]
	}
	return name
}
