"""Minimal application notes (Obsidian-compatible YAML frontmatter)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

DEFAULT_BODY = """# {company} — {position}

- Folder: `{folder}`
- Job: {job_url}
- PR: {pr}
"""


def split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---"):
        return {}, text
    rest = text[3:]
    end = rest.find("\n---")
    if end < 0:
        return {}, text
    raw_fm = rest[:end]
    body = rest[end + 4 :]
    if body.startswith("\n"):
        body = body[1:]
    loaded = yaml.safe_load(raw_fm) or {}
    if not isinstance(loaded, dict):
        return {}, text
    return loaded, body


def dump_note(frontmatter: dict[str, Any], body: str) -> str:
    cleaned = {k: v for k, v in frontmatter.items() if v not in (None, "", [])}
    dumped = yaml.safe_dump(
        cleaned,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
    ).strip()
    body = body.lstrip("\n")
    if body and not body.endswith("\n"):
        body += "\n"
    return f"---\n{dumped}\n---\n\n{body}"


def default_body(properties: dict[str, Any]) -> str:
    return DEFAULT_BODY.format(
        company=properties.get("company") or "Unknown",
        position=properties.get("position") or "Unknown",
        folder=properties.get("folder") or "",
        job_url=properties.get("job_url") or "—",
        pr=properties.get("pr") or "—",
    )


def upsert_note(
    tracker: Path,
    name: str,
    properties: dict[str, Any],
    extra_body: str | None = None,
) -> Path:
    tracker.mkdir(parents=True, exist_ok=True)
    safe = Path(name).name
    if not safe or safe in {".", ".."}:
        raise ValueError(f"invalid note name: {name!r}")
    path = tracker / f"{safe}.md"
    existing_fm: dict[str, Any] = {}
    body = ""
    if path.is_file():
        existing_fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
    merged = {**existing_fm, **{k: v for k, v in properties.items() if v not in (None, "")}}
    if not body.strip() and extra_body:
        body = extra_body
    path.write_text(dump_note(merged, body), encoding="utf-8")
    return path


def write_index(tracker: Path) -> Path:
    tracker.mkdir(parents=True, exist_ok=True)
    rows: list[dict[str, Any]] = []
    for path in sorted(tracker.glob("*.md")):
        if path.name == "Applications.md":
            continue
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            continue
        rows.append(
            {
                "name": path.stem,
                "company": fm.get("company") or path.stem,
                "position": fm.get("position") or "",
                "status": fm.get("status") or "Draft",
                "applied": fm.get("applied") or fm.get("created") or "",
            }
        )
    lines = [
        "# Applications",
        "",
        "> Generated by the pipeline MCP / `make obsidian`. Edit individual notes, not this table.",
        "",
        "| Company | Position | Status | Applied | Note |",
        "|---------|----------|--------|---------|------|",
    ]
    for row in rows:
        lines.append(
            f"| {row['company']} | {row['position']} | {row['status']} "
            f"| {row['applied']} | [[{row['name']}]] |"
        )
    if not rows:
        lines.append("| — | — | — | — | — |")
    lines += [
        "",
        "```dataview",
        "TABLE company, position, status, applied",
        'WHERE type = "application"',
        "SORT applied DESC",
        "```",
        "",
    ]
    index = tracker / "Applications.md"
    index.write_text("\n".join(lines), encoding="utf-8")
    return index
