/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current readiness state of the service including CV path accessibility, allowed target count, running job queue depth, and AI provider key availability.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Returns all metrics in Prometheus text exposition format (text/plain). Intended for scraping by a Prometheus server.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validates credentials and sets a JWT session cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clears the session cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve audit log
         * @description Returns the last 100 audit entries in reverse-chronological order. Requires authentication. The buffer is in-memory and not persisted across server restarts.
         */
        get: operations["getAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["listApplications"];
        put?: never;
        /** Create application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bulk update applications
         * @description Patches the same set of fields on multiple applications in a single request. Per-application errors are collected and returned rather than causing the whole operation to fail.
         */
        patch: operations["bulkUpdateApplications"];
        trace?: never;
    };
    "/api/applications/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export all applications
         * @description Exports all applications as JSON (default) or CSV. The CSV includes a header row with columns: name, company, position, status, created_at.
         */
        get: operations["exportApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get application */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update application */
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/api/applications/{name}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application notes
         * @description Returns the raw content of the application's notes.md file.
         */
        get: operations["getNotes"];
        /**
         * Update application notes
         * @description Writes content to notes.md. Creates a versioned backup of the previous content before overwriting.
         */
        put: operations["updateNotes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/notes/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List note versions
         * @description Returns metadata for all historical versions of the application's notes.md.
         */
        get: operations["listNoteVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/notes/versions/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get note version
         * @description Returns the content of a specific historical notes.md version.
         */
        get: operations["getNoteVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload file */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download file
         * @description Serves a raw file from the application directory.
         */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/skills-gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skills gap analysis
         * @description Compares keywords from the application's job.txt against cv.yml and returns missing and present skills.
         */
        get: operations["getSkillsGap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/health-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CV health audit
         * @description Analyses the application's notes.md file and returns quality scores: quantification_score (% of bullet points containing numbers/metrics), action_verb_score (% of bullet points starting with strong action verbs), completeness_score (100 if notes exist and have > 100 chars, else 0), and overall_score (average of the three).
         */
        get: operations["getHealthAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/health-audit/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health audit history
         * @description Returns the stored historical health audit scores for an application.
         */
        get: operations["getHealthAuditHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CV preview PDF
         * @description Generates a themed PDF preview for the application via cv-runner and streams the PDF back. Requires the 'preview' Make target to be configured.
         */
        get: operations["getPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{name}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cached job match score
         * @description Returns the most recent AI job match analysis result for the application. Returns 404 if no match has been run yet.
         */
        get: operations["getJobMatch"];
        put?: never;
        /**
         * Execute job match AI analysis
         * @description Runs the AI-powered job match scoring pipeline for the application. Optionally accepts AI provider and minimum threshold in the request body. Results are cached and retrievable via GET.
         */
        post: operations["runJobMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search
         * @description Performs full-text search across all application files. Returns matching applications with file-level snippets.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard overview
         * @description Returns aggregated dashboard data including application counts by status and recent applications.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline statistics
         * @description Returns funnel data and application timeline statistics.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List CV themes
         * @description Returns all available CV presentation themes.
         */
        get: operations["listThemes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Make target */
        post: operations["executeAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job status
         * @description Returns the status of a running or completed Make target job.
         */
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Make targets
         * @description Returns all allowed Make targets from the configuration.
         */
        get: operations["listTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings */
        get: operations["getSettings"];
        /** Update settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download backup
         * @description Streams a tar.gz archive of the entire applications directory. Requires admin role.
         */
        get: operations["getBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore from backup
         * @description Accepts a multipart tar.gz upload and extracts it into the applications directory, overwriting existing files. Maximum upload size: 100 MB. Requires admin role.
         */
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns all active (non-expired) JWT sessions. Requires admin role.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke session
         * @description Revokes a JWT session by its ID (jti). Requires admin role.
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns prefix and role information for all stored API keys. Full key values are never returned. Requires admin role.
         */
        get: operations["listAPIKeys"];
        put?: never;
        /**
         * Generate API key
         * @description Creates a new API key and returns the full value exactly once. The key is added to the runtime store immediately. Requires admin role.
         */
        post: operations["generateAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/api-keys/{prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke API key
         * @description Revokes all API keys matching the given prefix. Requires admin role.
         */
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE stream
         * @description Server-Sent Events stream for real-time Make target output. Authenticates via token query parameter or session cookie. Requires at least editor role.
         */
        get: operations["sseStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/actions/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket stream
         * @description WebSocket connection for real-time Make target output. Authenticates via token query parameter or session cookie during handshake. Requires at least editor role.
         *     Protocol: - Client sends ActionRequest JSON as first message - Server sends WSMessage with type "stdout", "stderr", "exit", or "error" - Connection closes after the Make process exits
         */
        get: operations["wsStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Always "ok" when the server is reachable.
             * @example ok
             */
            status: string;
            /** @description True when the RUNNER_UP env var is set to "true". */
            runner_up: boolean;
            /** @description True when CV_PATH exists and is accessible. */
            cv_path_ok: boolean;
            /** @description Number of allowed Make targets loaded from the config. */
            targets_count: number;
            /** @description Number of jobs currently in the running state. */
            job_queue_depth: number;
            /** @description Map of provider name to whether its API key/host is configured. */
            ai_providers: {
                gemini?: boolean;
                anthropic?: boolean;
                openai?: boolean;
                mistral?: boolean;
                ollama?: boolean;
            };
        };
        AuditEntry: {
            /**
             * Format: date-time
             * @description UTC timestamp when the event occurred.
             */
            time: string;
            /**
             * @description The type of security-relevant event.
             * @enum {string}
             */
            action: "login" | "logout" | "action_execute" | "app_create" | "app_update" | "file_upload" | "settings_update";
            /** @description The affected resource name (application name, target, etc.). */
            resource?: string;
            /** @description The authenticated username or "api_key". */
            user?: string;
            /** @description Client IP address (port stripped, X-Forwarded-For respected). */
            ip?: string;
            /**
             * @description Outcome of the event.
             * @enum {string}
             */
            result: "ok" | "denied" | "error";
            /** @description Additional context about the event. */
            detail?: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
            /** @description TOTP code (required when TOTP is configured) */
            totp?: string;
        };
        LoginResponse: {
            token: string;
            /** @description Unix timestamp when the token expires. */
            expires_at: number;
        };
        Application: {
            name?: string;
            company?: string;
            position?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            deadline?: string;
            outcome?: string;
            files?: {
                [key: string]: string;
            };
        };
        CreateApplicationRequest: {
            company: string;
            position: string;
            url?: string;
        };
        UpdateApplicationRequest: {
            status?: string;
            company?: string;
            position?: string;
            followup_date?: string;
            deadline?: string;
        };
        NotesResponse: {
            /** @description Raw markdown content of notes.md */
            content: string;
        };
        WriteNotesRequest: {
            /** @description New markdown content for notes.md */
            content: string;
        };
        NoteVersion: {
            /** @description Version filename (e.g. notes-2024-03-15T10-30-00.md) */
            filename: string;
            /**
             * Format: date-time
             * @description When this version was created
             */
            created_at: string;
            /** @description File size in bytes */
            size: number;
        };
        ActionRequest: {
            application?: string;
            args?: {
                [key: string]: string;
            };
        };
        ActionResult: {
            job_id: string;
            target: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            exit_code: number;
            stdout?: string;
            stderr?: string;
            duration_ms: number;
        };
        UploadResponse: {
            ok: boolean;
            filename: string;
        };
        OKResponse: {
            ok: boolean;
        };
        Settings: {
            theme?: string;
            default_view?: string;
            /** @description Default AI provider to use for Make targets (e.g. gemini, claude, openai, mistral, ollama) */
            default_ai?: string;
            /** @description Default model name for the selected AI provider */
            default_model?: string;
        };
        APIError: {
            code: number;
            message: string;
        };
        BulkUpdateRequest: {
            /** @description Application names to update */
            names: string[];
            update?: components["schemas"]["UpdateApplicationRequest"];
        };
        BulkUpdateResponse: {
            /** @description Number of applications successfully updated */
            updated: number;
            /** @description Per-name error messages for any failures */
            errors: string[];
        };
        SkillsGapResponse: {
            /** @description Keywords found in job.txt but not in cv.yml */
            missing: string[];
            /** @description Keywords found in both job.txt and cv.yml */
            present: string[];
        };
        HealthAuditScores: {
            /** @description Percentage of bullet points that contain numbers or metrics (e.g. "20%", "$1M", "3x"). */
            quantification_score: number;
            /** @description Percentage of bullet points that start with a strong action verb. */
            action_verb_score: number;
            /** @description 100 when notes.md exists and has more than 100 characters, else 0. */
            completeness_score: number;
            /** @description Average of the three scores above. */
            overall_score: number;
        };
        HealthAuditResponse: {
            /** @description Application name */
            application: string;
            scores: components["schemas"]["HealthAuditScores"];
            /**
             * Format: date-time
             * @description UTC timestamp when the audit was performed
             */
            checked_at: string;
        };
        HealthAuditHistoryResponse: {
            /** @description Application name */
            application: string;
            /** @description Historical health audit score entries */
            history: {
                /** Format: date-time */
                checked_at?: string;
                quantification_score?: number;
                action_verb_score?: number;
                completeness_score?: number;
                overall_score?: number;
            }[];
        };
        SearchMatch: {
            /** @description Filename where the match was found */
            file: string;
            /** @description Text snippet containing the match */
            snippet: string;
        };
        SearchResult: {
            /** @description Application directory name */
            name: string;
            company: string;
            position: string;
            /** @description Current application stage/status */
            stage: string;
            /** @description File-level matches within this application */
            matches: components["schemas"]["SearchMatch"][];
        };
        SearchResponse: {
            results: components["schemas"]["SearchResult"][];
        };
        JobMatchRequest: {
            /**
             * @description AI provider to use (e.g. gemini, claude, openai, mistral, ollama)
             * @example gemini
             */
            ai?: string;
            /**
             * @description Minimum match score threshold (0-100)
             * @example 60
             */
            threshold?: number;
        };
        /** @description AI job match analysis result. Structure depends on the pipeline output. */
        JobMatchResponse: {
            /** @description Overall match score (0-100) */
            score?: number;
            /** @description Configured minimum threshold */
            threshold?: number;
            /** @description AI provider used for analysis */
            ai_provider?: string;
            /** @description Skills found in both CV and job description */
            matched_skills?: string[];
            /** @description Skills required by job but not found in CV */
            missing_skills?: string[];
            /** @description AI-generated analysis text */
            analysis?: string;
        };
        DashboardResponse: {
            total_applications: number;
            /** @description Count of applications grouped by status */
            by_status: {
                [key: string]: number;
            };
            /** @description Most recently created applications */
            recent_applications: components["schemas"]["Application"][];
            /** @description Total AI provider calls across all executions (included when metrics are available) */
            ai_provider_calls_total?: number;
        };
        TimelineEntry: {
            /** @description Date in YYYY-MM-DD format */
            date: string;
            /** @description Number of applications created on this date */
            count: number;
        };
        StatsData: {
            /** @description Application counts at each pipeline stage */
            funnel: {
                [key: string]: number;
            };
            timeline: components["schemas"]["TimelineEntry"][];
        };
        Target: {
            /** @description Make target name */
            name: string;
            /** @description Target category for grouping */
            category: string;
            /** @description Human-readable description of what the target does */
            description: string;
            /** @description Required argument names */
            args?: string[];
            /** @description Timeout override (e.g. "5m", "30s") */
            timeout?: string;
        };
        Theme: {
            /**
             * @description Machine-readable theme identifier
             * @example tech-blue
             */
            name: string;
            /**
             * @description Human-readable theme name
             * @example Tech Blue
             */
            display_name: string;
            /**
             * @description Primary colour as a CSS hex value
             * @example #0066CC
             */
            primary_color: string;
            /**
             * @description Base font size used by this theme
             * @example 11pt
             */
            font_size: string;
            /** @description Short description of the theme's aesthetic and intended use */
            description: string;
        };
        Session: {
            /** @description Session identifier (JWT jti claim) */
            id: string;
            /** @description Username the session belongs to */
            subject: string;
            /**
             * @description RBAC role assigned to this session
             * @enum {string}
             */
            role: "viewer" | "editor" | "admin";
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Client user agent string */
            user_agent?: string;
            /** @description Client IP address */
            ip?: string;
        };
        SessionListResponse: {
            sessions: components["schemas"]["Session"][];
        };
        APIKeyInfo: {
            /** @description First 8 characters of the API key */
            prefix: string;
            /**
             * @description RBAC role assigned to this key
             * @enum {string}
             */
            role: "viewer" | "editor" | "admin";
            /**
             * Format: date-time
             * @description When the key was created
             */
            added_at: string;
        };
        APIKeyListResponse: {
            keys: components["schemas"]["APIKeyInfo"][];
        };
        GenerateAPIKeyRequest: {
            /**
             * @description Role to assign to the new key (defaults to editor)
             * @default editor
             * @enum {string}
             */
            role: "viewer" | "editor";
        };
        GenerateAPIKeyResponse: {
            /** @description Full API key value (returned exactly once) */
            key: string;
            /** @description First 8 characters of the key */
            prefix: string;
            /**
             * @description Role assigned to this key
             * @enum {string}
             */
            role: "viewer" | "editor";
        };
        RestoreResponse: {
            /** @description Number of files restored */
            restored: number;
            /** @description Human-readable summary */
            message: string;
        };
        WSMessage: {
            /**
             * @description Message type
             * @enum {string}
             */
            type: "stdout" | "stderr" | "exit" | "error";
            /** @description Message payload (output text, exit code, or error message) */
            data: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Access denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Request entity too large */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: {
        /** @description Application directory name (e.g. 2024-03-acme-engineer) */
        AppName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text format metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                /** @description Filter by exact status value (e.g. applied, interviewing, rejected) */
                status?: string;
                /** @description Filter by case-insensitive company name substring */
                company?: string;
                /** @description Field to sort by (default created_at) */
                sort?: "created_at" | "deadline" | "company" | "status";
                /** @description Sort direction (default desc) */
                order?: "asc" | "desc";
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Pagination cursor (application name) from X-Next-Cursor header */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated application list */
            200: {
                headers: {
                    /** @description Total number of matching applications (before pagination) */
                    "X-Total-Count"?: number;
                    /** @description Cursor value to pass as ?cursor= for the next page. Absent when the current page is the last one. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Created application */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    bulkUpdateApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Bulk update result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkUpdateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    exportApplications: {
        parameters: {
            query?: {
                /** @description Export format */
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exported applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description Updated application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notes content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteNotesRequest"];
            };
        };
        responses: {
            /** @description Notes updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listNoteVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of note version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteVersion"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getNoteVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
                /** @description Version filename (e.g. notes-2024-03-15T10-30-00.md) */
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note version content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
                /** @description Filename within the application directory */
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSkillsGap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skills gap analysis results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsGapResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getHealthAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health audit scores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthAuditResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getHealthAuditHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health audit score history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthAuditHistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getPreview: {
        parameters: {
            query: {
                /** @description CV theme to use for the preview */
                theme: "tech-blue" | "startup-orange" | "executive-dark" | "cyber-red" | "minimal-clean" | "academic-classic";
            };
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Preview target not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    getJobMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job match analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMatchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    runJobMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application directory name (e.g. 2024-03-acme-engineer) */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobMatchRequest"];
            };
        };
        responses: {
            /** @description Job match analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMatchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            /** @description Job match target not configured */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query (minimum 3 characters) */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsData"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of themes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Theme"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    executeAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Target completed synchronously */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Target accepted and running */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job identifier returned by executeAction */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of allowed Make targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    restoreBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description tar.gz backup file
                     */
                    backup: string;
                };
            };
        };
        responses: {
            /** @description Restore completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session ID (JWT jti claim) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of API keys (prefixes only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    generateAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateAPIKeyRequest"];
            };
        };
        responses: {
            /** @description API key generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateAPIKeyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Key prefix (first 8 characters) */
                prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sseStream: {
        parameters: {
            query?: {
                /** @description JWT session token (alternative to cookie auth) */
                token?: string;
                /** @description Application name to pass to the target */
                app?: string;
            };
            header?: never;
            path: {
                /** @description Make target name to execute */
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of WSMessage events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["WSMessage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    wsStream: {
        parameters: {
            query?: {
                /** @description JWT session token for authentication */
                token?: string;
            };
            header?: never;
            path: {
                /** @description Make target name to execute */
                target: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket upgrade successful */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
