target-version = "py39"
line-length = 120

[lint]
select = ["E", "F", "W"]
ignore = ["E501", "E741", "E402", "E731"]

[lint.per-file-ignores]
"tests/*" = ["E", "F", "W"]
"scripts/*" = ["F541", "F401", "F841"]
